sudo: false
language: java
before_install:
- wget http://www.deflaker.org/maven/apache-maven-3.5.0.zip
- unzip -qq apache-maven-3.5.0.zip
- export M2_HOME=$PWD/apache-maven-3.5.0
- export PATH=$M2_HOME/bin:$PATH
- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
notifications:
  email: false
  slack:
    rooms: flakycov:U2MeVOPjdi4up1U793ubeIUZ
    template:
    - Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}
    - 'dashbot: %{repository_name} %{build_id}'
install: 
  # use mvn ≥ 3.3.9 to ensure faulty test exit states fail the build (#1276)
  - mvn -B -N io.takari:maven:wrapper -Dmaven=3.5.0
  # download and install Cloud SDK (may be cached)
  - build/install-cloudsdk.sh 171.0.0 $HOME
# Tycho ≥ 0.26 requires Java 8
jdk: oraclejdk8
env:
  matrix:
    # ECLIPSE_TARGET is the targeted platform: mars is the default target
    # JAVA_RUNTIME specifies the execution runtime for tests; must match an <id> in .travis-toolchains.xml
    - JAVA_RUNTIME=JavaSE-1.7
    - JAVA_RUNTIME=JavaSE-1.8 ECLIPSE_TARGET=neon
    - JAVA_RUNTIME=JavaSE-1.8 ECLIPSE_TARGET=oxygen MAVEN_FLAGS=-Pjacoco
  global:
    - PATH=$PWD/google-cloud-sdk/bin:$PATH
    # Our maven build typically reports about 512m
    - MAVEN_OPTS=-Xmx700m
    - CLOUDSDK_CORE_DISABLE_USAGE_REPORTING=true
    - DISPLAY=:99.0
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - metacity --sm-disable --replace &
  - sleep 3 # give metacity some time to start
script: mvn -V -B -Ptravis --fail-at-end verify ${MAVEN_FLAGS}
     ${ECLIPSE_TARGET:+-Declipse.target=${ECLIPSE_TARGET}}
     --toolchains=.travis-toolchains.xml
     -Dtoolchain.java.runtime=${JAVA_RUNTIME}
addons:
  apt:
    packages:
      - metacity
cache:
  directories:
   - $HOME/.m2
   - $HOME/google-cloud-sdk
after_success:
  # test req'd as we don't run coverage on all elements of the matrix
  - if [ -d build/jacoco/target ]; then bash <(curl -s https://codecov.io/bash); fi
